name: Proton GE init

permissions:
  contents: write

env:
  GH_TOKEN: ${{ github.token }}

on:
  schedule:
    - cron:  '0 0 */3 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Build Wine
        run: |
          git clone --recurse-submodules http://github.com/gloriouseggroll/proton-ge-custom wine
      - uses: actions/upload-artifact@v4
        with:
          name: PROTON-GE SRC WoW64
          path: ./wine