name: Wine Stable

on:
  workflow_dispatch:

permissions:
  contents: write

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        continue-on-error: true
        with:
          workflow: bootstrap_wow64.yml
          workflow_conclusion: success
          path: /opt
      - name: Build Wine
        run: |
          sudo apt update
          sudo apt install debootstrap perl git wget xz-utils bubblewrap autoconf
          sudo tar -C /opt -xpf "/opt/Bootstraps WoW64/bootstraps_wow64.tar.xz"
          chmod +x build_wine.sh
          export WINE_VERSION="$(wget -q -O - "https://gitlab.winehq.org/wine/wine/-/raw/stable/VERSION" | tail -c +14)"
          WINE_BRANCH=vanilla ./build_wine.sh
          sha256sum *.tar.xz
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: Stable
          files: |
            ./wine-action-vanilla.tar.xz
