name: Build Wine-Staging 10.15

on:
  workflow_dispatch:  # 手动触发

jobs:
  build-wine-staging:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          git \
          wget \
          curl \
          automake \
          autoconf \
          libtool \
          libx11-dev \
          libxext-dev \
          libxi-dev \
          libxrandr-dev \
          libxcursor-dev \
          libxinerama-dev \
          libxxf86vm-dev \
          libxcomposite-dev \
          libxdamage-dev \
          libosmesa6-dev \
          libglu1-mesa-dev \
          libncurses5-dev \
          libsdl2-dev \
          libpulse-dev \
          libdbus-1-dev \
          libfontconfig1-dev \
          libfreetype6-dev \
          libgnutls28-dev \
          libjpeg-dev \
          libpng-dev \
          libtiff5-dev \
          libmpg123-dev \
          libopenal-dev \
          libvulkan-dev \
          libldap2-dev \
          gettext \
          bison \
          flex
        
    - name: Download Wine 10.15 source
      run: |
        wget https://dl.winehq.org/wine/source/10.x/wine-10.15.tar.xz
        tar -xf wine-10.15.tar.xz
        mv wine-10.15 wine-source
        
    - name: Clone Wine-Staging
      run: |
        git clone https://github.com/wine-staging/wine-staging.git
        cd wine-staging
        git checkout v10.15  # 对应 Wine 1.8.7 (10.15)
        
    - name: Apply Wine-Staging patches
      run: |
        cd wine-staging
        ./patches/patchinstall.sh DESTDIR=../wine-source --all
        
    - name: Build Wine
      run: |
        cd wine-source
        ./configure --enable-win64
        make -j$(nproc)
        
    - name: Create archive
      run: |
        tar -czf wine-staging-10.15-built.tar.gz wine-source/
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wine-staging-10.15
        path: |
          wine-staging-10.15-built.tar.gz
          wine-source/
        retention-days: 30
        
    - name: Setup download info
      run: |
        echo "Wine-Staging 10.15 build completed successfully!" > build-info.txt
        echo "Build date: $(date)" >> build-info.txt
        echo "Download the artifact named 'wine-staging-10.15' from the Actions tab." >> build-info.txt
        
    - name: Upload build info
      uses: actions/upload-artifact@v4
      with:
        name: build-info
        path: build-info.txt