name: Build Wine Staging 10.15 Source

on:
  workflow_dispatch

env:
  WINE_VERSION: "10.15"

jobs:
  build-wine-source:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git wget autoconf xz-utils \
          automake libtool make \
          flex bison gettext

    - name: Download and prepare Wine source
      run: |
        set -e
        
        export WINE_VERSION="10.15"
        export BUILD_DIR="$HOME/build_wine"
        
        # 清理并创建构建目录
        rm -rf "${BUILD_DIR}"
        mkdir -p "${BUILD_DIR}"
        cd "${BUILD_DIR}"
        
        echo "下载 Wine Staging 10.15 源码..."
        
        # 下载 Wine 10.15 源码
        wget -q "https://dl.winehq.org/wine/source/10.x/wine-${WINE_VERSION}.tar.xz"
        tar xf "wine-${WINE_VERSION}.tar.xz"
        mv "wine-${WINE_VERSION}" wine
        
        # 下载并应用 Staging 补丁
        wget -q "https://github.com/wine-staging/wine-staging/archive/v${WINE_VERSION}.tar.gz" -O "v${WINE_VERSION}.tar.gz"
        tar xf "v${WINE_VERSION}.tar.gz"
        
        cd wine
        
        # 应用 Staging 补丁
        if [ -f "../wine-staging-${WINE_VERSION}/patches/patchinstall.sh" ]; then
          "../wine-staging-${WINE_VERSION}/patches/patchinstall.sh" DESTDIR="${BUILD_DIR}/wine" --all
        else
          "../wine-staging-${WINE_VERSION}/staging/patchinstall.py" --all
        fi
        
        # 准备构建系统
        dlls/winevulkan/make_vulkan
        tools/make_requests
        tools/make_specfiles
        autoreconf -f
        
        cd "${BUILD_DIR}"
        
        echo "源码准备完成，创建源码包..."
        # 创建源码包
        tar -Jcf "wine-staging-${WINE_VERSION}-src.tar.xz" wine
        
        # 显示包信息
        echo "源码包信息:"
        ls -lh "wine-staging-${WINE_VERSION}-src.tar.xz"
        echo "源码包已创建: wine-staging-${WINE_VERSION}-src.tar.xz"
        
        # 列出构建目录内容，用于调试
        echo "构建目录内容:"
        ls -la "${BUILD_DIR}"

    - name: Upload source artifact
      uses: actions/upload-artifact@v4
      with:
        name: wine-staging-10.15-source
        path: $HOME/build_wine/wine-staging-10.15-src.tar.xz
        retention-days: 30

    - name: Show build info
      run: |
        echo "=== 源码打包完成 ==="
        echo "Wine 版本: 10.15 Staging"
        echo "模式: 仅打包源码"
        echo "构建产物: wine-staging-10.15-src.tar.xz"
        echo "已上传至 Artifacts"
        echo "================"